name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: ContactPoint.sln
      Configuration: Release

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@2008f912f56e61277eefaac6d1888b750582aa16

    - name: Restore application dependencies
      run: msbuild $env:Solution_Name -t:Restore -p:Configuration=$env:Configuration

    - name: Build
      run: msbuild $env:Solution_Name -t:Build -p:Configuration=$env:Configuration
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Binaries
        path: ../Binaries

    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Setup Appium
      run: npm install -g appium

    - name: Execute unit tests
      run: dotnet test -r ../TestResults -l trx
      env:
        APP_ARGUMENTS: /loglevel 10 /log ../TestResults/ipphone-log.txt
        
    - name: Upload test results
      uses: actions/upload-artifact@v1.0.0
      with:
        name: TestResults
        path: ../TestResults

    # Decode the base 64 encoded pfx and save the Signing_Certificate
#    - name: Decode the pfx
#      run: |
#        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
#        $certificatePath = Join-Path -Path $env:Wap_Project_Directory -ChildPath GitHubActionsWorkflow.pfx
#        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

    # Create the app package by building and packaging the Windows Application Packaging project
#    - name: Create the app package
#      run: msbuild $env:Wap_Project_Path /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:Appx_Package_Build_Mode /p:AppxBundle=$env:Appx_Bundle /p:PackageCertificateKeyFile=GitHubActionsWorkflow.pfx /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}
#      env:
#        Appx_Bundle: Always
#        Appx_Bundle_Platforms: x86|x64
#        Appx_Package_Build_Mode: StoreUpload
#        Configuration: ${{ matrix.configuration }}

    # Remove the pfx
#    - name: Remove the pfx
#      run: Remove-Item -path $env:Wap_Project_Directory\$env:Signing_Certificate

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-artifact
#    - name: Upload build artifacts
#      uses: actions/upload-artifact@v1
#      with:
#        name: MSIX Package
#        path: ${{ env.Wap_Project_Directory }}\AppPackages
